"""
constants.py - TITAN Wave 1
Hard-coded system constants. Cannot be changed at runtime.
"""
from enum import Enum

INVITE_ONLY = True
ADMIN_APPROVAL_REQUIRED = True
MAX_TOTAL_USERS = 6
WAVE = 1
ADMIN_PIN_LENGTH = 6
ADMIN_PIN_MAX_ATTEMPTS = 3
ADMIN_PIN_LOCKOUT_SECONDS = 1800
ADMIN_SESSION_DURATION_HOURS = 12
INVITE_TOKEN_EXPIRY_HOURS = 48
RATE_LIMIT_MESSAGES = 10
RATE_LIMIT_WINDOW_SECONDS = 10
MAX_MESSAGE_LENGTH = 4000

LEAK_PROTECTED_TERMS = [
    "api key", "api secret", "private key", "seed phrase",
    "mnemonic", "secret key", "access key", "password"
]

class UserState(str, Enum):
    PENDING_APPROVAL = "PENDING_APPROVAL"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    SUSPENDED = "SUSPENDED"
    REJECTED = "REJECTED"

class AuditAction(str, Enum):
    USER_JOINED = "USER_JOINED"
    USER_APPROVED = "USER_APPROVED"
    USER_REJECTED = "USER_REJECTED"
    USER_SUSPENDED = "USER_SUSPENDED"
    USER_RESUMED = "USER_RESUMED"
    USER_PAUSED = "USER_PAUSED"
    ADMIN_LOGIN = "ADMIN_LOGIN"
    ADMIN_LOGIN_FAILED = "ADMIN_LOGIN_FAILED"
    ADMIN_LOCKOUT = "ADMIN_LOCKOUT"
    CONFIG_CHANGED = "CONFIG_CHANGED"
    INVITE_GENERATED = "INVITE_GENERATED"
    INVITE_USED = "INVITE_USED"
    LEAK_DETECTED = "LEAK_DETECTED"
    BROADCAST_SENT = "BROADCAST_SENT"
    SYSTEM_STARTED = "SYSTEM_STARTED"
    SYSTEM_STOPPED = "SYSTEM_STOPPED"
    USER_STATE_CHANGED = "USER_STATE_CHANGED"